### ISSUE TITLE
Split Learning

### ISSUE THREAD

**Issue by kazumasan144** [Minki-Kim95/Federated-Learning-and-Split-Learning-with-raspberry-pi#1]
Hi,

I notice that in your paper, you mentioned that there are 26,490 samples for 5 classes of heart beat for the ECG data. Inside your code, each of the  26,490 samples has 130 features. May I please ask if there is more information about these features such as what do these feature represent?

Thank you!

**Comment by Minki-Kim95** [comment]
There are only 5 heartbeat types (5 classes) in ECG dataset
![image](https://user-images.githubusercontent.com/37619253/97001285-186ab200-1573-11eb-9ce0-0fe32905577a.png)

I think 130 is just length of heart beat. you can understand what I say by upper image.

If you want more detail about ECG dataset, you can reference this paper "Personalized Monitoring and Advance Warning System for Cardiac Arrhythmias" what we referenced.
